config/routes.rb
Rails.application.routes.draw do
  root 'awards#index'
  resource :awards, only: [:index]
  get 'awards/repo_awards', to: 'awards#repo_awards'
  get 'awards/diplom', to: 'awards#diplom'
  get 'awards/download_zip', to: 'awards#download_zip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
  end

  def repo_awards
    result = GetTopContributors.call(repo: params[:link])
    if result.success?
      @contributors = result.contributors
    else
      flash[:error] = result.message
      redirect_to action: 'index'
    end
  end

  def diplom
    contrib = params[:contrib]
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "diplom",
               locals: {contrib: contrib},
               layout: 'wicked_pdf.pdf'
      end
    end
  end

  def download_zip
    require 'zip'
    contribs = params[:contribs]
    stringio = Zip::OutputStream.write_buffer do |zio|
      contribs.each do |contrib|
        #create and add a pdf file for this record
        dec_pdf = render_to_string pdf: "#{contrib[:author][:login]}.pdf",
                                   template: 'awards/diplom.pdf',
                                   locals: {contrib: contrib},
                                   layout: 'wicked_pdf.pdf'
        zio.put_next_entry("#{contrib[:author][:login]}.pdf")
        zio << dec_pdf
      end
    end
    # This is needed because we are at the end of the stream and
    # will send zero bytes otherwise
    stringio.rewind
    #just using variable assignment for clarity here
    binary_data = stringio.sysread
    send_data(binary_data, type: 'application/zip', filename: "diplomas.zip")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/awards/_contributor.slim
.contrib class="place-#{contrib[:place]}"
  = link_to awards_diplom_path(format: :pdf, contrib: contrib), class: 'pdf_diplom', target: '_blank'
    = fa_icon 'file-pdf', size: '3x'

  .place-name
    h1
      = contrib[:place]
      |  Place
  = link_to contrib[:author][:html_url] do

    = image_tag contrib[:author][:avatar_url]
    .login = contrib[:author][:login]


  span
    = contrib[:total]
    |  commits


  .clearfix

app/views/awards/diplom.pdf.slim
.pdf.contrib style=''
  h1
    = contrib[:place]
    |  Place

  = link_to contrib[:author][:html_url] do

    = image_tag contrib[:author][:avatar_url]
    br
    = contrib[:author][:login]

  br
  span = contrib[:total]
  .big_text Congratulations!

app/views/awards/index.slim
H2 Enter Github repository path
= form_tag "awards/repo_awards", method: :get, class: 'repo_form' do
  = text_field_tag :link, 'https://github.com/rails/rails', class: 'input_link'
  = submit_tag 'Get Awards', class: 'button'

app/views/awards/repo_awards.slim
h1 Top contributors
span
  = "Repo: "
  = link_to @link, @link

= render partial: 'contributor', collection: @contributors, as: :contrib
= link_to awards_download_zip_path(contribs: @contributors), class: 'button center', target: '_blank'
  = fa_icon 'file-archive'
  |   Download ZIP
= link_to 'Back', root_path, class: 'button center light'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Github Awards
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .box
      .error
        - flash.each do |name, msg|
          = content_tag :div, msg, class: name
      = yield

app/views/layouts/wicked_pdf.pdf.slim
doctype html
html
  head
    = wicked_pdf_stylesheet_link_tag "pdf"
    / = wicked_pdf_javascript_include_tag "number_pages"
  body onload="number_pages" 
    / #header
    /   = wicked_pdf_image_tag 'mysite.jpg'
    #content
      = yield